### ISSUE TITLE
Suggestion: can the S-Bahn line box be homogeneous in size?

### ISSUE THREAD

**Issue by Rudd-O** [neuhausf/lovelace-swiss-stationboard#5]
I've noticed that the boxes aren't uniform in size.  If CSS is used to make these table cells (or grid, or even flex), they should be uniform in size.

**Comment by neuhausf** [comment]
Hm, I'm not sure if this looks better?
![image](https://user-images.githubusercontent.com/7963239/199286146-2bfd2f33-89bf-4e72-a3d5-458c084a5ff5.png)
Current version:
![image](https://user-images.githubusercontent.com/7963239/199286254-4f63b08b-4188-4331-9594-b0c746b8d914.png)
In the SBB it's displayed with a symbol + text:
![image](https://user-images.githubusercontent.com/7963239/199286528-cbb36248-37d8-473a-9c42-fec7011fff1a.png)

**Comment by Rudd-O** [comment]
Oh.  Now you've given me ideas.  It would be phenomenal if it looked exactly like these assets in the app / page.

**Comment by Rudd-O** [comment]
That said, the homogeneous look looks better at least in my view.
