### ISSUE TITLE
Could the "Gleis" word be omitted?

### ISSUE THREAD

**Issue by Rudd-O** [neuhausf/lovelace-swiss-stationboard#6]
In the interest of leaving more horizontal space (for narrow screens like mobile devices), can an option be afforded that would suppress the word "Gleis" in the column of the railway?  Thanks in advance.

**Comment by neuhausf** [comment]
Probably I should add an option to set the railway name. So you could use an abbrev. like "Gl." in the SBB app (or omit it alltogether).

**Comment by Rudd-O** [comment]
Das wäre super.

**Comment by neuhausf** [comment]
Use the new option "platform_name" to set a specific abbrevation for the track/railway/platform. If not set, no name is shown.

**Comment by Rudd-O** [comment]
Das isch super!  Danke vielmals!
